### ISSUE TITLE
Filter by IEDs

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-communication-editor#26]
We're interested in using this plugin to visualize communications.

Recently we've been exploring having our Protection 1 and Protection 2 system in the same SCD file.

It would be great to have say our standard IED button and a filtered list where the user could choose which IEDs they wanted to include.

**Comment by JakobVogelsang** [comment]
You mean filter not only connection but complete IEDs?

**Comment by danyill** [comment]
Yes, for instance typically our Protection 1 IEDs and MUs finish with a "1" and have few connections to our Protection 2 IEDs and MUs which finish with a "2".

We usually do autoreclose initiate and block between line protection from Protection 1 to Protection 2 but otherwise they are not connected.

I suspect the display will be too cluttered to view both Protection 1 and Protection 2 IEDs on the same diagram at the same time.

**Comment by JakobVogelsang** [comment]
Would it be enough then to filter on the connections - not show connections of specific IED, or do you think it would be better to not show IED in the SLD. Until now I though that we can always leave those in and only filter on connection.

**Comment by danyill** [comment]
Yes, I think we can try that to begin with in which case we want to filter connections associated with particular IEDs.

**Comment by JakobVogelsang** [comment]
Is implemented
